# fly.toml app configuration file generated for fullstack-cicd-bloglist on 2025-01-03T02:30:16+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fullstack-cicd-bloglist'
primary_region = 'arn'

[build]

[processes]
  app = "node index.js"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
